---
name: CI Tests

'on':
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests with pytest
        run: |
          echo "Running pytest..."
          pytest tests/ -v

      - name: Check code formatting with black
        run: |
          echo "Checking code formatting..."
          black --check src/

      - name: Lint code with ruff
        run: |
          echo "Running linter..."
          ruff check src/

      - name: Summary
        if: success()
        run: |
          echo "✅ All checks passed successfully!"
