---
name: Fetch AI Models

'on':
  # Run daily at midnight UTC
  schedule:
    - cron: '0 0 * * *'

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      provider:
        description: >-
          Provider to fetch from
          (all, openrouter, anthropic, openai, google)
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - openrouter
          - anthropic
          - openai
          - google

jobs:
  fetch-models:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Fetch models
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          PROVIDER="${{ github.event.inputs.provider }}"
          # Use 'all' if no input provided (scheduled run)
          if [ -z "$PROVIDER" ]; then
            PROVIDER="all"
          fi

          echo "Fetching models from provider: $PROVIDER"
          fetcher fetch --provider "$PROVIDER"

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code data/ || \
            echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/

          PROVIDER="${{ github.event.inputs.provider }}"
          if [ -z "$PROVIDER" ]; then
            PROVIDER="all"
          fi

          TIMESTAMP=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
          MSG="Update model catalog from $PROVIDER provider(s)"
          MSG="$MSG\n\nAutomated update via GitHub Actions"
          MSG="$MSG - Triggered: $TIMESTAMP"
          git commit -m "$MSG"

          git push

      - name: Summary
        if: always()
        run: |
          if [ "${{ steps.git-check.outputs.has_changes }}" == "true" ]; then
            echo "✅ Model catalog updated successfully"
          else
            echo "ℹ️ No changes detected in model catalog"
          fi
